data_engineer_challenge:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "localhost"
      user: "{{ env_var('DBT_POSTGRES_USER') }}"
      password: "{{ env_var('DBT_POSTGRES_PASSWORD') }}"
      port: 5433
      dbname: "default"
      schema: "public"
      threads: 4